---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
# TODO: Make this a generic gateway for the monitoring namespace
# EG; monitoring.bramble/grafana || monitoring.bramble/prometheus
# forward to the respective service
metadata:
  name: grafana-gateway
  namespace: monitoring # Or your preferred gateway namespace
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "grafana.bramble"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "grafana.bramble"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: grafana-bramble-cert
            namespace: monitoring
      allowedRoutes:
        namespaces:
          from: Same
