apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

labels:
  - includeSelectors: false
    pairs:
      owner: bramble
      environment: minibramble

helmCharts:
  - name: grafana
    repo: https://grafana-community.github.io/helm-charts
    version: 11.3.6
    releaseName: grafana
    namespace: monitoring
    skipHooks: true
    valuesFile: grafana-values.yaml

  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 28.14.1
    releaseName: prometheus
    namespace: monitoring
    skipHooks: true
    valuesFile: prometheus-values.yaml

resources:
  - namespace.yaml
  - dashboards/ # Folder containing your JSON-to-ConfigMap manifests
  - gateway.yaml
  - httproute.yaml
  - tlsroute.yaml
  - grafana-cert.yaml
  # - authorization-policies.yaml
