---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  parentRefs:
    - name: grafana-gateway
      sectionName: https
      namespace: monitoring
  hostnames:
    - "grafana.bramble"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: grafana
          port: 80
          weight: 1
