[crusts]
raspberrypi_01  ansible_ssh_host=192.168.1.81
raspberrypi_02  ansible_ssh_host=192.168.1.86
raspberrypi_03  ansible_ssh_host=192.168.1.195
raspberrypi_04  ansible_ssh_host=192.168.1.61
raspberrypi_05  ansible_ssh_host=192.168.1.13

[miners]
uminer01 ansible_ssh_host=192.168.1.136