#cloud-config

hostname: black-bramble-01    #change this as needed to reflect hostnames?
manage_etc_hosts: true
apt_preserve_sources_list: true

locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

users:
  - name: skylar                # use any user name you like
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    ssh-import-id: None
    plain_text_passwd: __insert_pass__
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa __insert_key__   # insert your SSH public key ~/.ssh/id_rsa.pub here

# # WiFi connect to HotSpot
# # - use `wpa_passphrase SSID PASSWORD` to encrypt the psk
write_files:
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=us
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid="__ADD_SSID__"
      psk="__ADD_PASSWORD__"
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'

  # Activate WiFi interface
  - 'ifup wlan0'

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - ntp
  - vim

power_state:
  mode: reboot
