apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: peer
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: arm32v7/redis
        command: [sh, -c, source /redis-config/init.sh]
        ports: 
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: config
          mountPath: /redis-config
        - name: data
          mountPath: /redis-data
      - name: sentinel
        image: arm32v7/redis
        command: [sh, -c, source /redis-config/sentinel.sh]
        volumeMounts:
          - mountPath: /redis-config
            name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config
        name: config
      - emptyDir:
        name: data
