apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
  labels:
    chapter: secrets
spec:
  containers:
  - name: kuard-tls
    image: gcr.io/kuar-demo/kuard-arm:1
    imagePullPolicy: Always
    resources:
        requests:
          cpu: 25m
          memory: 5Mi
        limits:
          cpu: 100m
          memory: 500Mi
    volumeMounts:
      - name: tls-certs
        mountPath: /tls
        readOnly: true
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
  restartPolicy: Never

