apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: arm32v7/ghost
        volumeMounts:
          - mountPath: /ghost-config
            name: config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: ghost-config
