# TODO: Setup as a istio ingress
# TODO: Troubleshoot DNS record not resolving to service (accessible via IP)
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kiali.bramble
  name: kiali
spec:
  type: LoadBalancer
