# Setup Guide @
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# TODO: configure external dns to gateway resources of class istio
namespace: externaldns-system

# TODO: Secret has to be generated manually, how to automate
# secretGenerator:
#   - name: pihole-password
#     files:
#       - .env.pihole
#       kubectl create secret generic -n externaldns-system pihole-password --from-literal EXTERNAL_DNS_PIHOLE_PASSWORD=supersecret

resources:
  - namespace.yaml
  - external-dns.yaml
