---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-selfsigned-cert
  namespace: cert-manager
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: bramble-ca-issuer
