---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Are these required for Istio?
  # server.insecure: "true"
  # controller.repo.server.plaintext: "true"
