---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bramble-kiali-operator
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/siolta/rPi_cluster.git
    targetRevision: master
    path: k8s/kiali-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: [CreateNamespace=true]
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
