# ArgoCD Applications - Managed by root app (path varies by overlay)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bookinfo.yaml
  - metal-lb.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - istio.yaml
