# Istio travel-demo application: https://kiali.io/docs/tutorials/travels/02-install-travel-demo/
# TODO: Add a Istio based ingress solution
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      owner: bramble
      environment: minibramble

resources:
  - []
