# Istio Sample application: https://istio.io/latest/docs/ambient/getting-started/deploy-sample-app/
# TODO: Add a Istio based ingress solution
# TODO: Add external-dns host support
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo-test

labels:
  - includeSelectors: false
    pairs:
      owner: bramble
      environment: minibramble

resources:
  - namespace.yaml
  # - authorization-policies.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.29/samples/bookinfo/platform/kube/bookinfo.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.29/samples/bookinfo/gateway-api/bookinfo-gateway.yaml
  # Defines available versions as services so istio can control versioned traffic
  - https://raw.githubusercontent.com/istio/istio/release-1.29/samples/bookinfo/platform/kube/bookinfo-versions.yaml

patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations/external-dns.alpha.kubernetes.io~1hostname"
        value: "bookinfo.bramble"
    target:
      kind: Gateway
      name: bookinfo-gateway
